### ISSUE TITLE
Plugin not working with Gradle 7.0

### ISSUE THREAD

**Issue by donbeave** [allure-framework/allure-gradle#60]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request

#### What is the current behavior?

```bash
../gradlew clean allureReport

> Task :tailrocks-payment-api-test:allureReport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':tailrocks-payment-api-test:allureReport' (type 'AllureReport').
  - Type 'AllureReport' property 'clean' has redundant getters: 'getClean()' and 'isClean()'.

    Reason: Boolean property 'clean' has both an `is` and a `get` getter.

    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#redundant_getters for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 618ms
3 actionable tasks: 1 executed, 2 up-to-date
```

#### Please tell us about your environment:

| Allure version | 2.13.9 |
| --- | --- |
| Test framework | junit5 |
| Generate report using | allure-gradle@2.8.1 |

**Comment by patrykks** [comment]
This not the only problem. Plugin is using for example testCompile keyword which was removed in Gradle 7.0. Details: https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#sec:configuration_removal 

Is this project still supported/maintained? In few months this issue will be blocker for all users that would like to use version Gradle in version >=7.0. With these version Gradle brings new important features such as support for Java 16 or native support for new generation of MAC processors.

**Comment by patrykks** [comment]
Are community contributions into this repository allowed?

**Comment by vlsi** [comment]
This PR adds Gradle 7.0 compatibility: https://github.com/allure-framework/allure-gradle/pull/61

**Comment by Ankhell** [comment]
> This not the only problem. Plugin is using for example testCompile keyword which was removed in Gradle 7.0. Details: https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#sec:configuration_removal
> 
> Is this project still supported/maintained? In few months this issue will be blocker for all users that would like to use Gradle in version >=7.0. Gradle in 7.0 brings important features such as support for Java 16 or native support for new generation of MAC processors.

This one is not a blocker, actually, you can use
```
    allure {
        configuration = "testImplementation"
    }
 ```

**Comment by Ankhell** [comment]
> This PR adds Gradle 7.0 compatibility: #61
> 
> Please feel free to try it and provide feedback

Unfortunately jitpack fails to build it :( 

![image](https://user-images.githubusercontent.com/59031542/118950901-4b3b2400-b963-11eb-878b-514463e96268.png)
[Jitpack report](https://jitpack.io/com/github/vlsi/allure-gradle/facelift-2.8.1-g64d7bd8-16/build.log)

**Comment by vlsi** [comment]
Thanks. I've pushed a fix in https://github.com/allure-framework/allure-gradle/pull/61/commits/cb07f416f57eafc5cdb5c2dfe16bb7dfcff82bdc

**Comment by cheparsky** [comment]
Why did you downgrade Gradle to 6.9?

We use the last version of Gradle, will it be compatible and fix the problem?

**Comment by KroArtem** [comment]
@vlsi , do you by accident know whether there are plans on releasing a new version?

**Comment by martenhellmann** [comment]
Could you please publish/build a new release from the current state. Last published release is from 2019. Thank you!

**Comment by KroArtem** [comment]
@baev , @eroshenkoam , currently this is a blocker to use gradle 7, is there any chance for new version?

**Comment by pandoras-toolbox** [comment]
We are also waiting for a bug fix. Or is there a workaround so that we can used Gradle 7 with Allure?

**Comment by nareshiot** [comment]
We have recently upgraded to Gradle 7 and with the above mentioned issue unable to generate the Allure report. Is there any release scheduled to resolve this issue? Or please suggest if there are any workaround to make it work with Gradle 7 version.

**Comment by alexsirko** [comment]
@baev @eroshenkoam Looks like a lot of people anticipating a new release :) It would be very good to have at least a bit of backwards communication ;)

**Comment by szczebel** [comment]
+1 to bump up priority of Gradle 7.x support

**Comment by mformetal** [comment]
Any idea when this may happen? Would love to use AGP 7.0 in my project with this plugin.

**Comment by admizh** [comment]
summon nobody, seems like need create fork

**Comment by KroArtem** [comment]
During umoney meetup (https://youtu.be/s-cXhMcYwQM) @eroshenkoam said they'll have a look at this issue together with @baev but still no activity. It does look very impolite to promise something and do nothing, though 😞

**Comment by eroshenkoam** [comment]
<img width="897" alt="Screenshot 2021-09-20 at 23 13 53" src="https://user-images.githubusercontent.com/781455/134069027-4a11234b-3db1-46fd-924a-461d2f5c4c25.png">
It's almost done)

**Comment by eroshenkoam** [comment]
Waiting for approval)

**Comment by KroArtem** [comment]
Nice to hear!

**Comment by vlsi** [comment]
Looks like the plugins have been approved for the Gradle Plugin Portal: https://plugins.gradle.org/search?term=io.qameta.allure

**Comment by eroshenkoam** [comment]
<img width="824" alt="Screenshot 2021-09-23 at 13 12 58" src="https://user-images.githubusercontent.com/781455/134490332-39cdf5ae-7e0b-4537-8670-9dcda4e06fa5.png">
Gradle miss `allure-base` plugin, to we need to wait until it will be approved.

**Comment by eroshenkoam** [comment]
ty, fixed in 2.9.3

**Comment by davidmoshal** [comment]
Problem still exists with Grade 7.2
Pity, the Node JS reporter works nicely.
Guess it's not that well maintained?

**Comment by vlsi** [comment]
@davidmoshal , would you provide a reproducer?
There are integration tests with Gradle 7.2: https://github.com/allure-framework/allure-gradle/blob/master/allure-plugin/src/test/kotlin/io/qameta/allure/gradle/report/TestAndAllureReportTest.kt#L41

**Comment by suchitra-srinivasan** [comment]
`Some problems were found with the configuration of task ':allureAggregatedReport' (type 'AllureReport').
  - In plugin 'io.qameta.allure' type 'io.qameta.allure.gradle.task.AllureReport' property 'clean' has redundant getters: 'getClean()' and 'isClean()'.`
 
Gradle version:  7.4.2

**Comment by zatolokinboris** [comment]
Столкнулся с той же проблемой, при обновлении проекта командой разработки на 7.4.2 отвалился allure. Есть ли примерное понимания когда будет исправлена проблема?

**Comment by vlsi** [comment]
@zatolokinboris , давно исправлено уже. Какая у вас версия плагина?

**Comment by zatolokinboris** [comment]
> 

Версия гредл плагина 7.2.0

**Comment by unickq** [comment]
Gradle 7.4.2

```js
plugins {
  id 'io.qameta.allure' version '2.10.0'
}

allure {
  version = '2.18.1'
}
```

`./gradlew allureServe --info`


```
Task :tests:allureServe NO-SOURCE
Skipping task ':colleague-hub-tests:allureServe' as it has no source files and no previous output files.
:colleague-hub-tests:allureServe (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
producer locations for task group 0 (Thread[Execution worker for ':',5,main]) started.
producer locations for task group 0 (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
```

Update from gradle 6. Missing source files?

**Comment by vlsi** [comment]
Have you tried `./gradlew allureServe --depends-on-tests`?

@unickq , please do not add issues as comments to an old issue. It triggers excessive notifications.
